import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import Typist from 'react-typist';
import Button from '../components/Button'
import Link from 'next/link'
const Stars = dynamic(() => import("../components/Stars"), { ssr: false });

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Join | Hidden Stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
          <Stars />
          <header className='flex flex-col items-center md:space-y-3 space-y-1'>
            <h1 className='text-white md:text-6xl text-3xl font-bold'>
              <span className='text-blue-500'>Join</span> The Hidden Stars
            </h1>
            <Typist cursor={{ show: false }}>
              <h1 className='text-white md:text-6xl text-3xl font-bold'>
                Movement <span className='text-blue-500'>Today</span>.
              </h1>
            </Typist>
            <div className='flex flex-col w-screen px-5 justify-center !mt-8'>
              <h2 className='text-white text-center'>
                We are all stars! Sometimes we are just hidden in the crowd. 
              </h2>
            </div>
            <div className='flex space-x-3 md:space-x-5 !mt-10 w-full justify-center'>
              <Link href={"https://discord.com/invite/CA9AEyWSGr"} passHref>
                <a target={"_blank"} rel="noopener noreferrer">
                  <Button className="!mr-0 w-[140px] md:min-w-[150px]">Discord Server</Button>
                </a>
              </Link>
              <span className='h-10 w-[2px] bg-gray-400 rounded-lg'></span>
              <Link href={"#about"}>
                <Button mode='secondary' className="w-[140px] md:min-w-[150px]">Learn More</Button>
              </Link>
            </div>
          </header>
        {/* <iframe width="560" height="315" src="https://www.youtube.com/embed/KdiJ9zqiMn4" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> */}
      </main>
      <Footer />
    </div>
  )
}

export default Home
