import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import Typist from 'react-typist';
const Stars = dynamic(() => import("../components/Stars"), { ssr: false });

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Join | Hidden Stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
          <Stars />
          <header className='flex flex-col items-center md:space-y-3 space-y-1'>
            <h1 className='text-white md:text-6xl text-3xl font-bold'>
              <span className='text-blue-500'>Join</span> The Hidden Stars
            </h1>
            <Typist>
              <h1 className='text-white md:text-6xl text-3xl font-bold'>
                Movement <span className='text-blue-500'>Today</span>.
              </h1>
            </Typist>
            <div className='flex flex-col w-screen px-5 justify-center'>
              <h2 className='text-white text-center'>
                We are all stars! Sometimes we are just hidden in the crowd. 
              </h2>
            </div>
          </header>
        {/* <iframe width="560" height="315" src="https://www.youtube.com/embed/KdiJ9zqiMn4" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> */}
      </main>
      <Footer />
    </div>
  )
}

export default Home
